export const FETCH_ADD_CUSTOMER_REQUEST = 'FETCH_ADD_CUSTOMER_REQUEST';
export const FETCH_ADD_CUSTOMER_SUCCESS = 'FETCH_ADD_CUSTOMER_SUCCESS';
export const FETCH_ADD_CUSTOMER_FAILURE = 'FETCH_ADD_CUSTOMER_FAILURE';

export const FETCH_CUSTOMER_LIST_REQUEST = 'FETCH_CUSTOMER_LIST_REQUEST';
export const FETCH_CUSTOMER_LIST_SUCCESS = 'FETCH_CUSTOMER_LIST_SUCCESS';
export const FETCH_CUSTOMER_LIST_FAILURE = 'FETCH_CUSTOMER_LIST_FAILURE';

export const FETCH_DELETE_CUSTOMER_REQUEST = 'FETCH_DELETE_CUSTOMER_REQUEST';
export const FETCH_DELETE_CUSTOMER_SUCCESS = 'FETCH_DELETE_CUSTOMER_SUCCESS';
export const FETCH_DELETE_CUSTOMER_FAILURE = 'FETCH_DELETE_CUSTOMER_FAILURE';

export const FETCH_CUSTOMER_DETAIL_REQUEST = 'FETCH_CUSTOMER_DETAIL_REQUEST';
export const FETCH_CUSTOMER_DETAIL_SUCCESS = 'FETCH_CUSTOMER_DETAIL_SUCCESS';
export const FETCH_CUSTOMER_DETAIL_FAILURE = 'FETCH_CUSTOMER_DETAIL_FAILURE';


export const FETCH_UPDATE_CUSTOMER_REQUEST = 'FETCH_UPDATE_CUSTOMER_REQUEST';
export const FETCH_UPDATE_CUSTOMER_SUCCESS = 'FETCH_UPDATE_CUSTOMER_SUCCESS';
export const FETCH_UPDATE_CUSTOMER_FAILURE = 'FETCH_UPDATE_CUSTOMER_FAILURE';
