export const FETCH_GENERE_LIST_REQUEST = 'FETCH_GENERE_LIST_REQUEST';
export const FETCH_GENERE_LIST_SUCCESS = 'FETCH_GENERE_LIST_SUCCESS';
export const FETCH_GENERE_LIST_FAILURE = 'FETCH_GENERE_LIST_FAILURE';


export const FETCH_ADD_GENERE_REQUEST = 'FETCH_ADD_GENERE_REQUEST';
export const FETCH_ADD_GENERE_SUCCESS = 'FETCH_ADD_GENERE_SUCCESS';
export const FETCH_ADD_GENERE_FAILURE = 'FETCH_ADD_GENERE_FAILURE';


export const FETCH_GENERE_DETAIL_REQUEST = 'FETCH_GENERE_DETAIL_REQUEST';
export const FETCH_GENERE_DETAIL_SUCCESS = 'FETCH_GENERE_DETAIL_SUCCESS';
export const FETCH_GENERE_DETAIL_FAILURE = 'FETCH_GENERE_DETAIL_FAILURE';


export const FETCH_UPDATE_GENERE_REQUEST = 'FETCH_UPDATE_GENERE_REQUEST';
export const FETCH_UPDATE_GENERE_SUCCESS = 'FETCH_UPDATE_GENERE_SUCCESS';
export const FETCH_UPDATE_GENERE_FAILURE = 'FETCH_UPDATE_GENERE_FAILURE';


export const FETCH_DELETE_GENERE_REQUEST = 'FETCH_DELETE_GENERE_REQUEST';
export const FETCH_DELETE_GENERE_SUCCESS = 'FETCH_DELETE_GENERE_SUCCESS';
export const FETCH_DELETE_GENERE_FAILURE = 'FETCH_DELETE_GENERE_FAILURE';
