export const FETCH_MOVIES_LIST_REQUEST = 'FETCH_MOVIES_LIST_REQUEST';
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS';
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE';

export const FETCH_ADD_MOVIES_REQUEST = 'FETCH_ADD_MOVIES_REQUEST';
export const FETCH_ADD_MOVIES_SUCCESS = 'FETCH_ADD_MOVIES_SUCCESS';
export const FETCH_ADD_MOVIES_FAILURE = 'FETCH_ADD_MOVIES_FAILURE';

export const FETCH_DELETE_MOVIES_REQUEST = 'FETCH_DELETE_MOVIES_REQUEST';
export const FETCH_DELETE_MOVIES_SUCCESS = 'FETCH_DELETE_MOVIES_SUCCESS';
export const FETCH_DELETE_MOVIES_FAILURE = 'FETCH_DELETE_MOVIES_FAILURE';

export const FETCH_MOVIES_DETAIL_REQUEST = 'FETCH_MOVIES_DETAIL_REQUEST';
export const FETCH_MOVIES_DETAIL_SUCCESS = 'FETCH_MOVIES_DETAIL_SUCCESS';
export const FETCH_MOVIES_DETAIL_FAILURE = 'FETCH_MOVIES_DETAIL_FAILURE';

export const FETCH_UPDATE_MOVIES_REQUEST = 'FETCH_UPDATE_MOVIES_REQUEST';
export const FETCH_UPDATE_MOVIES_SUCCESS = 'FETCH_UPDATE_MOVIES_SUCCESS';
export const FETCH_UPDATE_MOVIES_FAILURE = 'FETCH_UPDATE_MOVIES_FAILURE';