export const FETCH_ADD_RENTAL_REQUEST = 'FETCH_ADD_RENTAL_REQUEST';
export const FETCH_ADD_RENTAL_SUCCESS = 'FETCH_ADD_RENTAL_SUCCESS';
export const FETCH_ADD_RENTAL_FAILURE = 'FETCH_ADD_RENTAL_FAILURE';

export const FETCH_RENTAL_LIST_REQUEST = 'FETCH_RENTAL_LIST_REQUEST';
export const FETCH_RENTAL_LIST_SUCCESS = 'FETCH_RENTAL_LIST_SUCCESS';
export const FETCH_RENTAL_LIST_FAILURE = 'FETCH_RENTAL_LIST_FAILURE';

export const FETCH_DELETE_RENTAL_REQUEST = 'FETCH_DELETE_RENTAL_REQUEST';
export const FETCH_DELETE_RENTAL_SUCCESS = 'FETCH_DELETE_RENTAL_SUCCESS';
export const FETCH_DELETE_RENTAL_FAILURE = 'FETCH_DELETE_RENTAL_FAILURE';

export const FETCH_RENTAL_DETAIL_REQUEST = 'FETCH_RENTAL_DETAIL_REQUEST';
export const FETCH_RENTAL_DETAIL_SUCCESS = 'FETCH_RENTAL_DETAIL_SUCCESS';
export const FETCH_RENTAL_DETAIL_FAILURE = 'FETCH_RENTAL_DETAIL_FAILURE';
